#!/usr/bin/env python3
"""Validate a Xiaodu MCP workflow plan generated by plan_xiaodu_workflow.py."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ALLOWED_SERVER = "xiaodu"
ALLOWED_TOOLS = {
    "list_user_devices",
    "xiaodu_speak",
    "control_xiaodu",
    "query_xiaodu_skills",
    "xiaodu_open_skill",
    "push_resource_to_xiaodu",
    "xiaodu_take_photo",
    "xiaodu_record_video",
    "xiaodu_get_task",
}


def fail(msg: str) -> int:
    print(f"ERROR: {msg}", file=sys.stderr)
    return 1


def main() -> int:
    if len(sys.argv) != 2:
        return fail("usage: validate_xiaodu_plan.py <plan.json>")
    plan = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    steps = plan.get("steps")
    if not isinstance(steps, list) or not steps:
        return fail("plan.steps must be a non-empty list")

    seen_query = False
    seen_elder_reminder = False
    workflow = plan.get("workflow")
    for i, item in enumerate(steps, 1):
        server = item.get("server")
        tool = item.get("tool")
        args = item.get("arguments", {})
        if server != ALLOWED_SERVER:
            return fail(f"step {i} routes to {server!r}, expected {ALLOWED_SERVER!r}")
        if tool not in ALLOWED_TOOLS:
            return fail(f"step {i} uses unknown Xiaodu tool {tool!r}")
        if workflow == "elder-care" and tool == "control_xiaodu":
            command = str(args.get("command", ""))
            if "站立活动" in command and "放松眼睛" in command:
                seen_elder_reminder = True
        if tool == "query_xiaodu_skills":
            seen_query = True
            if not args.get("query"):
                return fail(f"step {i} query_xiaodu_skills requires non-empty query")
        if tool == "xiaodu_open_skill":
            if workflow == "elder-care" and not seen_elder_reminder:
                return fail(f"step {i} elder-care opens before stand-up and eye-relax reminder")
            if not seen_query:
                return fail(f"step {i} opens a skill before querying")
            app_key = str(args.get("app_key", ""))
            if not app_key:
                return fail(f"step {i} xiaodu_open_skill requires app_key placeholder or returned key")
            if "package" in app_key.lower() or app_key.startswith("com."):
                return fail(f"step {i} appears to use package name instead of returned app_key")
    print("OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
